# Generated by Django 3.1.8 on 2021-07-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentsapp', '0002_auto_20210722_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('comment_text', models.CharField(blank=True, max_length=100)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentsapp.comments')),
            ],
        ),
    ]
