# Generated by Django 3.1.8 on 2021-07-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repliesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
