# Generated by Django 3.1.8 on 2021-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('comments', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
